<?php

namespace Alpha\AlphaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * 
     * @param type $categoryToSearch the category names to be searched for
     * @return the categories searched
     */
    public function searchCategories($categoryToSearch) {
        //var_dump($categoryToSearch);die;
//        $em = $this->getDoctrine()->getManager();
            $qb = $this->createQueryBuilder('c');
            
            $res = $qb->select('c')
                    ->from('Category', 'c')
                    ->getQuery();

            echo '<pre>';print_r($res);die;
    }
}
