alpha_alpha_homepage:
    path:     /hello/{name}
    defaults: { _controller: AlphaAlphaBundle:Default:index }
#for user login
login:
    path:     /login
    defaults: { _controller: AlphaAlphaBundle:User:login }
#for user registration
signup:
    path:     /signup
    defaults: { _controller: AlphaAlphaBundle:User:signup }
#for user logout
logout:
    path:     /logout
    defaults: { _controller: AlphaAlphaBundle:User:logout }
#secured login page
profile:
    path:     /profile
    defaults: { _controller: AlphaAlphaBundle:Shop:profile }
    
#for category crud     
category:
    path:     /
    defaults: { _controller: "AlphaAlphaBundle:Category:index" }

category_show:
    path:     /{id}/show
    defaults: { _controller: "AlphaAlphaBundle:Category:show" }

category_new:
    path:     /new
    defaults: { _controller: "AlphaAlphaBundle:Category:new" }
    
category_new_ajax:
    path:     /new-ajax
    defaults: { _controller: "AlphaAlphaBundle:Category:newajax" }

category_create:
    path:     /create
    defaults: { _controller: "AlphaAlphaBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "AlphaAlphaBundle:Category:edit" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "AlphaAlphaBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "AlphaAlphaBundle:Category:delete" }
    requirements: { _method: post|delete }
    
category_search:
    path:     /category-search
    defaults: { _controller: "AlphaAlphaBundle:Category:search" }
    
    