parameters:
#    alpha_alpha.example.class: Alpha\AlphaBundle\Example

services:
#    alpha_alpha.example:
#        class: %alpha_alpha.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
